include:
- add-nsw-weather.zip
kind: ArchiveUploadSpec
name: add-nsw-weather-zip-gogW

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-nsw-weather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://add-nsw-weather-zip-gogW
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-14T02:46:37Z"
