include:
- Backend/weathers/nsw-wharvester.py
kind: ArchiveUploadSpec
name: backend-weathers-nsw-wharvester-py-Ausg

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: nsw-wharvester-76979ba8-782c-4711-9be6-e0ac64b646a3
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://backend-weathers-nsw-wharvester-py-Ausg
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T09:16:00Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: nsw-wharvester
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 600
  idletimeout: 120
  package:
    packageref:
      name: nsw-wharvester-76979ba8-782c-4711-9be6-e0ac64b646a3
      namespace: ""
  requestsPerPod: 1
  resources: {}
