include:
- ./Backend/air-quality-resp.zip
kind: ArchiveUploadSpec
name: backend-air-quality-resp-zip-mX24

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: air-quality-resp
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-air-quality-resp-zip-mX24
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-14T08:53:04Z"
