include:
- ./Backend/EPA_air_quality_harvester.zip
kind: ArchiveUploadSpec
name: backend-epa-air-quality-harvester-zip-IW2Z

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: epa-air-quality-harvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-epa-air-quality-harvester-zip-IW2Z
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-11T08:45:51Z"
