include:
- fission-functions/add-syd-weather.zip
kind: ArchiveUploadSpec
name: fission-functions-add-syd-weather-zip-PqgC

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-syd-weather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://fission-functions-add-syd-weather-zip-PqgC
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-12T08:44:51Z"
