include:
- Backend/weathers/add-vic-weather.zip
kind: ArchiveUploadSpec
name: backend-weathers-add-vic-weather-zip-89N5

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-vic-weather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-weathers-add-vic-weather-zip-89N5
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T08:54:13Z"
