include:
- Backend/suicide-data.zip
kind: ArchiveUploadSpec
name: backend-suicide-data-zip-IEcB

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: suicide-data
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-suicide-data-zip-IEcB
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T08:55:17Z"
