include:
- Backend/twitter-data.zip
kind: ArchiveUploadSpec
name: backend-twitter-data-zip-Ldlp

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: twitter-data
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-twitter-data-zip-Ldlp
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T08:56:03Z"
