include:
- Backend/weathers/add-nsw-weather.zip
kind: ArchiveUploadSpec
name: backend-weathers-add-nsw-weather-zip-m3y1

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: add-nsw-weather
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-weathers-add-nsw-weather-zip-m3y1
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T08:53:38Z"
