include:
- ./Backend/EPA_site_harvester.zip
kind: ArchiveUploadSpec
name: backend-epa-site-harvester-zip-ZfzG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: epa-site-harvester
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-epa-site-harvester-zip-ZfzG
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-11T05:04:14Z"
