include:
- Backend/traffic-injury.zip
kind: ArchiveUploadSpec
name: backend-traffic-injury-zip-DpCP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: traffic-injury
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://backend-traffic-injury-zip-DpCP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-21T08:55:43Z"
