apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: suicide-data
spec:
  createingress: false
  functionref:
    functionweights: null
    name: suicide-data
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /suicide-data
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /suicide-data
