apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: point-cook-router
spec:
  createingress: false
  functionref:
    functionweights: null
    name: add-vic-weather
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /weathers/point-cook
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /weathers/point-cook
