apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: twitter-data-router
spec:
  createingress: false
  functionref:
    functionweights: null
    name: twitter-data
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /twitter-data
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /twitter-data
