apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: epa-air-quality-harvester-trigger
spec:
  createingress: false
  functionref:
    functionweights: null
    name: epa-air-quality-harvester
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /EPA/air-quality
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /EPA/air-quality
