apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: melb-olympic-park-router
spec:
  createingress: false
  functionref:
    functionweights: null
    name: add-vic-weather
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /weathers/melb-olympic-park
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /weathers/melb-olympic-park
