apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-air-qualities-trigger
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-air-qualities
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /EPA/get-air-qualities
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /EPA/get-air-qualities
